### PR TITLE
Catch NoClassDefFoundError & bump version to 1.0.4 - fixes #13

### LINKED ISSUE #13: Catch NoClassDefFoundError at module initialization
Currently errors like the above caused by missing run-time dependencies will cause the entire Butterfly server to fail due to errors in a single module initialization. Instead the error should be caught and initialization of all error-free modules should continue.

### PR DESCRIPTION
**Pull request by tfmorris**
This will return the error and stack trace as an unstyled 500 page, but at least it:
- isn't hidden in the server log, and
- includes the name of the offending module and a more explicit error message

### CODE REVIEW

**Comment by wetneb** [comment]
Sorry for the delay in merging this, I will try to set up CI first for good measure.

**Review by wetneb — APPROVED** [review]

**Comment by wetneb** [comment]
Uploaded to Maven Central, it should be available in the coming hours.

**Comment by tfmorris** [comment]
@wetneb The publish to Maven Central doesn't appear to have worked https://mvnrepository.com/artifact/org.openrefine.dependencies/butterfly

**Comment by wetneb** [comment]
@tfmorris sorry about that, I indeed missed the last "release" step, which I just did now.

**Pull request merged**
