### PR TITLE
Build for Java 11 and 16 as well

### LINKED ISSUE #33: Compatibility with Java 16
Butterfly does not build with Java 16 yet.
https://github.com/OpenRefine/simile-butterfly/pull/32
This would be a prerequisite for OpenRefine to work with Java 16.
https://github.com/OpenRefine/OpenRefine/issues/4106

### PR DESCRIPTION
**Pull request by wetneb**
Attempt to check compatibility with newer versions of Java.

### CODE REVIEW

**Comment by wetneb** [comment]
Of course we have a really tiny test suite on this project, so there are still tons of incompatibilities that can still exist.
Given that no one else is active here I will just merge this, release it and see if it magically makes OpenRefine work with Java 16.

**Comment by thadguidry** [comment]
I'll test the snapshot or beta this morning. Just woke up.

**Comment by wetneb** [comment]
@thadguidry there is not much to test unfortunately, because updating OpenRefine to this new version of butterfly (1.2.0) does not solve the problem. So it could well be independent.

**Comment by thadguidry** [comment]
@wetneb OK understood

**Pull request merged**
